/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_dev_i2c_I2CAdapter */

#ifndef _Included_org_vesalainen_dev_i2c_I2CAdapter
#define _Included_org_vesalainen_dev_i2c_I2CAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vesalainen_dev_i2c_I2CAdapter
 * Method:    openAdapter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_dev_i2c_I2CAdapter_openAdapter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_vesalainen_dev_i2c_I2CAdapter
 * Method:    functionality
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_vesalainen_dev_i2c_I2CAdapter_functionality
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_vesalainen_dev_i2c_I2CAdapter
 * Method:    setAddress
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_i2c_I2CAdapter_setAddress
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
