/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_dev_i2c_I2CSMBus */

#ifndef _Included_org_vesalainen_dev_i2c_I2CSMBus
#define _Included_org_vesalainen_dev_i2c_I2CSMBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    writeQuick
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_writeQuick
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    readByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_readByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    writeByte
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_writeByte
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    readByteData
 * Signature: (IB)B
 */
JNIEXPORT jbyte JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_readByteData
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    writeByteData
 * Signature: (IBB)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_writeByteData
  (JNIEnv *, jobject, jint, jbyte, jbyte);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    readWordData
 * Signature: (IB)S
 */
JNIEXPORT jshort JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_readWordData
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    writeWordData
 * Signature: (IBS)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_writeWordData
  (JNIEnv *, jobject, jint, jbyte, jshort);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    readBlockData
 * Signature: (IB[BII)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_readBlockData
  (JNIEnv *, jobject, jint, jbyte, jbyteArray, jint, jint);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    writeBlockData
 * Signature: (IB[BII)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_writeBlockData
  (JNIEnv *, jobject, jint, jbyte, jbyteArray, jint, jint);

/*
 * Class:     org_vesalainen_dev_i2c_I2CSMBus
 * Method:    processCall
 * Signature: (IBS)S
 */
JNIEXPORT jshort JNICALL Java_org_vesalainen_dev_i2c_I2CSMBus_processCall
  (JNIEnv *, jobject, jint, jbyte, jshort);

#ifdef __cplusplus
}
#endif
#endif
