/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_dev_i2c_I2C */

#ifndef _Included_org_vesalainen_dev_i2c_I2C
#define _Included_org_vesalainen_dev_i2c_I2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vesalainen_dev_i2c_I2C
 * Method:    openAdapter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_dev_i2c_I2C_openAdapter
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
