/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_dev_FileIO */

#ifndef _Included_org_vesalainen_dev_FileIO
#define _Included_org_vesalainen_dev_FileIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vesalainen_dev_FileIO
 * Method:    open
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_dev_FileIO_open
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_vesalainen_dev_FileIO
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_dev_FileIO_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
